// ════════════════════════════════════════════════════════════
// Report pipeline feature flags
// ════════════════════════════════════════════════════════════
//
// Centralised toggles so server and client stay in sync.
// Flip a single constant when the new pipeline is wired in.

/**
 * When true, the in-app Approve button is disabled and the
 * /api/admin/report-drafts/[id]/approve endpoint refuses requests.
 *
 * Why: the auto-approve path currently calls the pdfkit-based
 * renderer (`renderLongFormReportPdfFromStub`) which produced a
 * broken 96-page document and is superseded by the new v1 HTML
 * template at `lib/report/templates/scale-code-diagnostic-v1/`.
 *
 * Until the new renderer is wired (Mac daemon + Chrome-headless
 * + template-fill pipeline), reports are generated by hand using
 * the template and uploaded back via a forthcoming manual flow.
 *
 * Flip to `false` once the new pipeline ships end-to-end.
 */
export const REPORT_AUTO_APPROVE_DISABLED = true

/**
 * Plain-English explanation shown to admins when they hit the
 * disabled Approve button. Keep it factual.
 */
export const REPORT_AUTO_APPROVE_DISABLED_MESSAGE =
  "Auto-approve is paused while the new report pipeline is rebuilt. " +
  "For now, generate the PDF by hand from the locked v1 template " +
  "(lib/report/templates/scale-code-diagnostic-v1/) and upload it via " +
  "the manual approval flow (coming next)."
