// 7 Forces Business Audit — vertical-specific overlays
// ════════════════════════════════════════════════════════════
// Each universal playbook (lib/audit/playbook.ts) is force-level.
// This file adds a vertical translation: for each {force × vertical}
// pair, 70–90 words that translate the universal logic into Monday-
// morning action for THAT specific business.
//
// The verdict page renders the overlay for the founder's vertical
// above the universal moves, under a "For your [vertical]" callout.
// Verticals not listed here (currently only "other") fall back to
// the universal-only experience.

import type { ForceKey, VerticalValue } from "./types"

export type OverlaySnippet = {
  content: string
}

export type VerticalOverlays = Record<ForceKey, OverlaySnippet>

export const PLAYBOOK_OVERLAYS: Partial<Record<VerticalValue, VerticalOverlays>> = {
  saas_b2b: {
    identity: { content: "Pick one ICP by company size, stack, and trigger event. \"Series A fintechs in India, 40–150 people, on AWS, just hired their first VP Eng\" beats \"mid-market SaaS.\" Kill the three logos you closed as favours that drag your roadmap sideways. Fire the free-tier hobbyists eating support hours. Your ICP-fit rate should hit 70%+ on new pipeline within 60 days, sales-cycle days should drop 30%. Stop chasing every inbound demo that doesn't match the cut. *If your demo deck works for both a 10-person startup and a 5000-person enterprise, you don't have a product — you have a pamphlet.*" },
    x_factor: { content: "Get five customers on a call and ask: \"Why didn't you just build this on Google Sheets?\" Their exact words become your refusal language. Name one barrier a copycat can't clone in 12 months — proprietary integrations, a workflow patent, a data network effect, a regulator certification. No single logo above 25% of ARR, or their renewal call is your board meeting. Kill the three roadmap items competitors also ship. NRR above 115% is the only proof your moat is real — not your pitch deck." },
    marketing: { content: "Own one word in the buyer's head — \"the audit tool for Indian CAs,\" not \"the workflow platform.\" Pick ONE distribution channel and bury the rest for 90 days: founder-led LinkedIn posting 4×/week to Heads of Eng, or SEO on 20 bottom-funnel comparison keywords, or partner referrals from 5 consultancies. Track cost per ICP-fit demo booked, not MQLs. Kill the webinar-podcast-newsletter-event stack you're half-doing. *If your CMO can't tell you CAC by channel this week, you don't have marketing — you have expenses.*" },
    sales: { content: "Build an offer prospects can't price-compare: bundle onboarding, custom integration, and a named CSM into one annual SKU. Run a 5-question discovery that makes them say the urgency out loud — \"what breaks at 3x volume?\" \"What did the last vendor miss?\" Write a disqualification line: \"We don't work with teams under 20 engineers — you'd waste money.\" Sales-cycle days should compress 40% in 60 days, free-trial-to-paid above 15%. Stop discounting to close the quarter — you're training the next renewal to ask for 30% off." },
    financial: { content: "Calculate true gross margin per customer after hosting, support, and CSM time — most Indian SaaS founders think it's 85% and it's actually 55% on the SMB tier. CAC payback under 12 months, LTV/CAC above 3, 18 months of runway in the bank. Fire the SMB tier eating support hours at ₹2K MRR. Stop the India-pricing-because-they-asked discount — your US lookalike charges 4×. Owner-inclusive profit margin should be 15%+ before you raise the next round. *Burn isn't a strategy — it's a countdown.*" },
    optimisation: { content: "Name the chokepoint: founder doing every demo, or solutions engineer bottlenecking onboarding, or support drowning in tier-1 tickets that should be in-app help. Build a self-serve onboarding flow that gets time-to-first-value under 7 days. Kill the three Slack channels nobody reads, the weekly all-hands that should be a Loom, the custom feature requests from one logo. Write one handover doc for the demo so an AE can run it without you. 10–15 hours back in the founder's week, measured by Friday." },
    scale: { content: "What breaks at 3× ARR? Usually it's the founder-led sales motion — you can't personally close 60 deals/quarter. Map the constraint: 3 AEs, a sales playbook, a marketing engine producing 100 ICP-fit demos/month, or infra that handles 10× load? Remove yourself from every demo above ₹5L ACV by month 3. Hire the VP Sales before you need them, not after the miss. NRR carries you through scale — not new logos — fix expansion motion first. Plan for the break, don't discover it in the board meeting." },
    owner_energy: { content: "Cut 50% of your daily decisions — pricing approvals under ₹10L, hiring below VP level, every feature request, every demo request, every LinkedIn DM. Default-no to investor coffee chats that aren't your lead. Block 9–10:30am for product or strategy, no Slack, no calls, 5 days a week. One full day a week — ideally Friday — where the team ships without you, no approvals, no demos, no fires. *If the company can't run without you for a Tuesday, it can't be sold, raised on, or scaled.*" },
  },

  agency_services: {
    identity: { content: "Pick one buyer your agency actually wins — a Series-A SaaS founder who needs paid ads, or a D2C brand at ₹5Cr stuck on creative — not both. Fire retainers under ₹1L/month, one-off logo gigs, and the \"we do everything\" page on your site. Kill the discovery call with anyone whose brief starts \"can you also...\". Measure repeat-client revenue percentage and average engagement size — if either is flat, your positioning is still mush. *The agency that serves everyone gets referred by no one.*" },
    x_factor: { content: "Write down, in your last 5 clients' own Slack messages, why they didn't go to a Fiverr freelancer or their cousin's nephew. That sentence is your refusal line — put it above the fold on your site and at the top of every proposal. Build one named barrier: a proprietary teardown, a category-specific POV, a published benchmark dataset. No single client above 25% of revenue, or they own you. *If a ChatGPT prompt can write your proposal, the prospect already has.*" },
    marketing: { content: "Own one word in one buyer's head: \"the paid-social agency for Indian D2C,\" not \"full-service digital.\" Distribution stack: founder LinkedIn with weekly case-study carousels showing real numbers; one teardown podcast with adjacent service partners (web devs, CRM consultants) who send you referrals; one industry stage per quarter. Kill SEO blog posts nobody reads and Instagram reels for other agencies. Track cost per qualified discovery call and source of last 10 closed deals — if referrals are 80%+, your marketing isn't working, your network is." },
    sales: { content: "Stop sending comparable proposals. Lead with a paid ₹25K–₹50K diagnostic — audit, teardown, roadmap — that becomes the engagement scope. Five questions before any pricing talk: what's broken, what have you tried, what's the cost of waiting six months, who else is in the room, what does success look like in 90 days. Disqualification line: \"if your budget is under ₹X/month, we're not a fit — here are two freelancers who are.\" Track proposal-to-close rate and days from first call to signed SOW. *Free pitches are how agencies train prospects to shop them.*" },
    financial: { content: "Calculate true gross margin per project: revenue minus every billable hour at fully loaded cost, including yours at ₹5K/hour minimum. Most agencies discover their \"flagship\" client is at 15% margin because of scope creep and revisions. Fire the bottom-quartile client this quarter. Track days-sales-outstanding — if clients pay at 60+ days, you're financing them; switch to 50% upfront, milestone billing, auto-debit. Hold three months of operating expenses in cash before any hire. *Lumpy project revenue is a choice; productised retainers are the fix.*" },
    optimisation: { content: "The chokepoint is almost always you reviewing junior work at 11pm. Name it. Build a written delivery playbook — discovery template, kickoff deck, weekly status format, revision policy capped at two rounds — so a mid-level can run a ₹3L/month account without your eyes. Kill internal status meetings, custom decks per client, and \"quick calls\" with prospects who haven't paid. Target: pull your owner-billable hours from 30/week to under 10. Track utilization rate of the team — under 65% means you've over-hired, over 85% means burnout is six weeks away." },
    scale: { content: "At 3× demand, the thing that breaks is your senior judgment on every deliverable. Map it: is the constraint people (no senior strategists in the market), system (no QA layer), or cash (no runway to hire ahead of revenue)? Most agencies cap because the founder is the only one clients trust on strategy calls. Remove yourself from one seat — pitch, delivery review, or account management — by training a second face and putting them on calls before you're ready. Track revenue per head; if it's under ₹40L, you're a body shop, not an agency." },
    owner_energy: { content: "Half your daily decisions are \"what font, which client first, approve this invoice.\" Kill them with a one-page brand kit, a Monday client-priority list, and a ₹50K spending limit your ops person owns. Block 9–11am for one deep-work output a day — a strategy deck, a hire decision, a sales letter — nothing else. One Friday a month, no Slack, no client calls, business runs without you. If it can't, you don't have an agency, you have a job with extra steps. *The founder bottleneck is the only ceiling that isn't market-imposed.*" },
  },

  ecom_d2c: {
    identity: { content: "Pick one buyer and write her down: the 28-year-old Tier-2 working mom buying her third kurta this quarter, or the gym-bro stacking whey every 45 days. Then kill the SKUs she doesn't buy, exit the marketplace that dilutes her (often Amazon for premium apparel), and stop running Meta ads to lookalikes of \"anyone with a pincode.\" Your repeat rate tells the truth about who you actually serve. *If your top 20% of customers can't describe your brand in one sentence, you don't have a brand — you have a Shopify store with ads.*" },
    x_factor: { content: "Write the one sentence your repeat customer would say about why she didn't buy the ₹300-cheaper dupe on Meesho. Not your founder story — her words, pulled from WhatsApp replies and review screenshots. Build one barrier a copycat can't clone in 30 days: a proprietary fabric blend, a 90-day wear guarantee, a community, a fulfilment SLA. Stop chasing the discount-hunter cohort. *Every rupee spent acquiring a sale-only buyer trains your CAC to rise and your margin to die.*" },
    marketing: { content: "Own one word in the category — \"breathable\" for innerwear, \"clean-label\" for supplements, \"under-₹999\" for occasionwear. Kill the 14-channel spray. Pick ONE distribution engine where you know CAC and ROAS by creative — usually Meta with weekly creative refresh and UGC reels, or micro-influencer seeding with trackable codes. Stop boosting posts. Stop \"brand awareness\" spends you can't tie to AOV. Track organic-to-paid ratio monthly. *If your ROAS only works at 40% off, you're not marketing — you're renting customers from Meta and Myntra.*" },
    sales: { content: "Your offer is your funnel. Stop competing on price on the PDP — bundle it (3-month skincare regimen, capsule wardrobe of 5 SKUs) so the buyer can't price-compare on Nykaa. Build a 5-question quiz (skin type, goal, usage frequency) that makes her state her own urgency before checkout. Disqualify: add a line that says \"not for occasional users.\" Fix the WhatsApp abandoned-cart flow — most D2C brands leak 60% of intent here. *Discount codes are not a sales strategy; they're a tax on your unwillingness to build an offer.*" },
    financial: { content: "Pull marketplace SKU-level P&L this week. Not GMV — CM2 after Myntra's 30%+ commission, COD return rate (often 25–40% on apparel), reverse logistics, discount, and ad cost allocated. You will find 30% of your SKUs are losing money and you're funding them with the winners. Fire those SKUs. Fire the marketplace where CM2 is negative. Know your true blended CAC, repeat rate at 90 days, and inventory days. *GMV is vanity; CM2 is the only number that pays your salary.*" },
    optimisation: { content: "Your chokepoint is almost never \"more sales.\" It's the founder approving every ad creative, the WhatsApp inbox no one owns, or the returns desk processing COD rejects manually. Map where 10–15 hours/week disappears. Kill three things: daily discount-code approvals, the \"festival sale\" planning meetings, the manual inventory reconciliation. Write one SOP for creative briefs and one for returns. Hand both off. *The bottleneck in most ₹5Cr D2C brands isn't traffic — it's the founder being the final approver on a 47-step operation.*" },
    scale: { content: "Pretend orders 3× next month. What breaks first? Usually it's fulfilment SLA, customer-care WhatsApp response time, or working capital tied up in inventory you can't reorder fast enough. Sometimes it's your one performance-marketing freelancer. Name it. Map the constraint — is it cash (inventory days too high), supply (one vendor for hero SKU), or system (no warehouse management beyond Excel)? Remove yourself from the creative approval seat first. *Most D2C brands don't die at ₹10Cr from low demand — they die from inventory cash traps and a founder who's still writing ad copy.*" },
    owner_energy: { content: "Half your daily decisions are creative approvals, discount sign-offs, and influencer DMs. Delete them. Pre-decide the discount calendar for the quarter — one document, no daily exceptions. Hand creative approval to one person with a written brief. Block 90 minutes every morning for the one thing only you can do: brand narrative, category bets, hiring. Take Sunday fully off — no Shopify dashboard, no Meta Ads Manager. *If your business needs you to approve a 10% off code at 11pm, you don't own a brand — the brand owns you.*" },
  },

  coaching_courses: {
    identity: { content: "Stop being the \"business coach for entrepreneurs\" or the \"fitness coach for everyone.\" Name one buyer: the 32-year-old salaried woman who tried three diets and is scared of the gym. Kill the low-ticket ₹499 ebook, the corporate workshop side-hustle, and the \"DM me for details\" leads who never convert. Your Reels pillars, webinar hook, and email subject lines all collapse into one person. *If your last 10 testimonials don't sound like the same human, you don't have a business — you have a content channel.*" },
    x_factor: { content: "Customers buy you over free YouTube for one reason — write it in their words, not yours. Build the named barrier a copycat coach can't clone in 30 days: a proprietary diagnostic, a closed cohort method, a results database with names. Fire the affiliate or JV partner driving more than 25% of launch revenue — that's a single point of failure. Refund rate above 8% means your X-factor is a promise, not a proof. *The free YouTube version is your competitor; \"more value\" is not an answer.*" },
    marketing: { content: "Pick one word you own — \"the salary-to-business coach,\" \"the no-cardio fat-loss method.\" Kill three of your five content pillars. Run one distribution lane hard: either Reels-to-webinar-to-DM, or YouTube-long-form-to-email-to-cohort. Know your cost per webinar registrant and per attendee, weekly. Organic-to-paid lead ratio should be at least 60-40 or the algorithm owns you. Stop posting daily \"value\" that trains buyers to expect everything free. *The Instagram gurus promising \"guaranteed 10X\" are not your competition — they're poisoning the well you drink from.*" },
    sales: { content: "Replace the ₹9,999 course with a named outcome offer — \"12-week salary-to-first-client system, weekly 1-1, results contract.\" Build a 5-question discovery script that makes the prospect say their own deadline and cost-of-inaction out loud. Add a disqualification line on the webinar: \"If you want passive income in 30 days, this is not for you.\" Webinar-to-buy below 4% means the offer is broken — not the traffic. Stop running ₹100 off coupons — discounting trains refunds. *A buyer who talks themselves in won't refund themselves out.*" },
    financial: { content: "Calculate true gross margin per student after ads, platform fees, payment gateway, support staff, and refund reserve — most coaches discover their ₹25,000 course nets ₹6,000. Course price ÷ CAC must be 3× or higher or you're renting students from Meta. Hold three months of operating expenses in cash before the next launch. Fire the cold-traffic funnel with 22% refund rate even if it looks like revenue. *Launch revenue minus refunds minus chargebacks minus next quarter's ad spend is the only number that pays your rent.*" },
    optimisation: { content: "Name the chokepoint: it's almost always you on sales calls, you in the community, you editing Reels. Kill the daily story posting, the manual onboarding emails, the WhatsApp DMs answered at midnight. One written SOP for cohort onboarding, one for refund handling, one for content publishing. Move community moderation to a paid lead student. Completion rate below 15% is a delivery system problem, not a student problem. *You don't have a scaling problem — you have a \"refusing to write things down\" problem.*" },
    scale: { content: "At 3× students, what breaks first — your sales calls, your community response time, your content output, or your delivery quality? Most coaches break at delivery because the \"premium\" promise was actually \"founder access.\" Map whether the constraint is your time, your team's training, or your tech stack. Remove yourself from the sales seat or the delivery seat — pick one. A cohort that depends on you for live calls will not survive going from 40 to 120 students. *Evergreen is not a funnel choice — it's an admission you've removed yourself from delivery.*" },
    owner_energy: { content: "Cut 50% of the decisions: pre-decide your content pillars for the quarter, your refund policy, your discovery call days, your launch calendar. One 90-minute deep block five mornings a week for offer-building or sales — phone off, no DMs, no Reels research. One full day a week where no student, no team member, no JV partner can reach you. The content treadmill is optional. *A coach who can't take Sunday off is selling freedom they don't own.*" },
  },

  manufacturing: {
    identity: { content: "Most manufacturing units chase every RFQ that hits the inbox and end up with 80 SKUs serving 40 dealers — none of them profitable. The One-Customer Cut means naming the exact buyer: \"mid-sized auto component OEMs in Pune doing ₹50Cr–₹200Cr who need zinc plating in under 7 days.\" Then fire the bottom 30% of dealers eating credit terms with no repeat orders, kill SKUs below 18% gross margin, and stop quoting on jobs where you're clearly the L3. *If your top-5 dealers are 60% of revenue, you don't have a business — you have five landlords.*" },
    x_factor: { content: "Chinese imports land 30% cheaper. You will never win on price — stop trying. The Refusal Sprint forces one sentence in your dealer's own words: \"I stay with them because they ship in 5 days when the China container takes 45.\" Build one named barrier — a tooling investment, a captive raw-material tie-up, a GST-compliant warehouse in their state. Cap any single dealer at 25% of revenue. Track repeat order rate per dealer monthly. *The procurement manager's L1 mindset is your villain — but his factory shutting down for stockout is your weapon.*" },
    marketing: { content: "Stop spending on Plast India booths that generate 200 cards and zero POs. Pick ONE word you own — \"7-day dispatch,\" \"GST-credit-clean,\" \"zero-rejection PPAP.\" Run one channel hard: either IndiaMART premium lead bidding with bid caps per category, OR procurement-manager LinkedIn outbound with 40 named accounts per BD per month, OR Google search for high-intent keywords (\"PVC granules supplier Mumbai 50kg\"). Measure cost-per-engaged-lead, not impressions. Kill trade shows that don't produce a tracked PO within 90 days. *One channel mastered beats four channels half-run.*" },
    sales: { content: "If your quote sits next to two others on the procurement manager's desk, you've already lost — he picks L1. Rebuild the offer so it can't be compared: bundle dispatch SLA, QC certificates, GST-compliant invoicing, and consignment stock into one PRT the buyer can't line-item against China. Run a 5-question RFQ investigation — lot size, rejection tolerance, payment terms, current vendor pain, dispatch criticality — that makes him state his own urgency. Disqualify any RFQ asking for 120+ day credit. Track RFQ-to-PO conversion weekly." },
    financial: { content: "Manufacturing's quiet killer is working capital days — 90 to 180 is normal, and it's eating the business alive. Compute true gross margin per SKU after raw material, freight, GST cycle losses, and rejection cost — not the inflated number your accountant shows. Then list dead stock above 180 days and liquidate at 40% to recover cash. Cap days sales outstanding at 75 with hard credit-stop rules. Fire one dealer demanding 90-day terms on 12% margin. Target 4 months of fixed costs in cash. *Revenue without collection is a hobby.*" },
    optimisation: { content: "The chokepoint is rarely the shop floor — it's usually dispatch documentation, GST invoicing, or QC sign-off creating 3-day delays that kill on-time delivery rate. Map the bottleneck for 10 days with a written log. Kill three tasks: the daily production review meeting nobody acts on, the manual reorder-level Excel the storekeeper updates, the courier-tracking calls. Hand over dispatch coordination to one named person with a written SOP. Target 95% on-time delivery and 10–15 hours back per week for the owner. *If you're still approving every PO above ₹50K, you're the bottleneck.*" },
    scale: { content: "At 3× demand, manufacturing breaks at one of five places: capacity utilization hitting 95% with no second-shift plan, working capital snapping when dealer orders 3× but payment terms stay 90 days, QC failing because the one trusted inspector can't be cloned, dispatch collapsing on documentation, or raw material supply choking on MOQ commitments to vendors. Name yours. Map it to time/team/system/cash/supply. Remove yourself from that critical seat — usually it's the founder personally clearing every dispatch or chasing every payment. Build the backup before you sign the next big PO." },
    owner_energy: { content: "The manufacturing founder's day is 60 WhatsApp messages from dealers, 20 dispatch approvals, 15 payment-follow-up calls, and 8 quote sign-offs — none of which build the business. Cut 50% by setting credit-limit rules nobody escalates, dispatch authority below ₹2L for the plant head, and a weekly dealer-call slot instead of constant interruptions. Block 90 minutes daily for one thing — costing, new dealer outreach, product development. Take one full Saturday off where the plant runs, dispatches happen, and payments clear without a single call to you." },
  },

  restaurant_fnb: {
    identity: { content: "Most restaurants try to be everything: birthday venue, biryani delivery, café date spot, late-night snack joint. Pick one. Name the human: \"weekday lunch crowd from the IT park 800m away\" or \"Sunday family dine-in within 3km.\" Kill the slow half of the menu — every SKU under 5% of weekly covers gets dropped or merged. Exit one aggregator promo that brings volume but no repeats. Cut the dishes you cook out of obligation, not demand. *If your menu has 80 items, your kitchen has 80 weaknesses and your customer has zero clarity.*" },
    x_factor: { content: "Why does a regular skip the cheaper place next door and walk into yours? Get the answer in their words — ask 10 repeat customers at the table, write the exact sentence. One named barrier a copycat can't clone in 30 days: a signature dish with a sourced ingredient, a chef's 12-year recipe, a service ritual. No single corporate account, society contract, or aggregator promo above 25% of monthly revenue. *If Zomato delisted you tomorrow, would anyone notice?*" },
    marketing: { content: "Own one word in a 3km radius — \"the filter coffee place,\" \"the Sunday brunch spot,\" \"the late-night biryani.\" One repeatable offer customers say out loud: \"weekday thali at 199.\" One distribution method with known cost per first-time footfall — pick ONE: Zomato Gold bid optimization, food blogger seeding (micro 10K–50K, 5 per month), society gate sampling within 2km, or Instagram Reels with a hook in 3 seconds. Refresh Google Maps photos monthly. Stop boosting random posts. *The aggregator owns your customer until you put a QR on the table.*" },
    sales: { content: "Your sale is two conversions: aggregator impression to order, and walk-in to repeat. On Zomato/Swiggy, the listing IS the pitch — first photo, first 6 words of menu name, first review on top. Fix those before raising the ad bid. For dine-in, the captain runs a 5-second investigation: \"first time here?\" If yes, suggest the signature, hand over a QR for 10% off next visit, capture WhatsApp. Disqualify the discount-hunter — don't chase ₹99 deal-site traffic that never returns. *Footfall without a phone number is a stranger you fed once.*" },
    financial: { content: "Run true gross margin dish-by-dish, not menu-average. Food cost under 33%, prime cost (food + labour) under 60%. Aggregator share above 40% of revenue is a red flag — you're renting your business from Zomato at 25% commission. Owner salary goes into the P&L before you call anything \"profit.\" Hold 3 months of rent + payroll in cash. Fire the bottom 20% of dishes by margin and the corporate catering account that pays in 90 days. *A full restaurant losing 4% per cover is a treadmill, not a business.*" },
    optimisation: { content: "Name the chokepoint: kitchen at 1.15pm, billing at 9.30pm, or the owner approving every Swiggy refund. Map hour-by-hour utilization — if lunch covers are 30% of dinner, you're paying rent for empty chairs. Kill 3 things this month: the printed menu reprints, the WhatsApp order-taking on the owner's phone, the daily mandi run a vendor could deliver. Cut table turn by 8 minutes via pre-bussing and QR billing. One written handover so the captain opens and closes without you. *Your kitchen doesn't need more hands — it needs fewer decisions per hour.*" },
    scale: { content: "Before opening outlet two, name what breaks at 3× demand. Usually it's the head chef — the recipes live in his head, not a spec sheet. Sometimes it's the cash cycle: Zomato pays in 7 days, rent and salaries don't wait. Map the constraint: standardised recipes with gram-level specs, a second-in-command trained for 90 days, central commissary for prep, or a 2-month working capital buffer. Pull yourself out of the daily indent and tasting. *A second location built on the first owner's reflexes is two restaurants both running at half capacity.*" },
    owner_energy: { content: "You're approving 200 micro-decisions a day: this paneer batch, that refund, this Instagram caption, that staff leave. Half can be killed with a one-page SOP and a captain who's allowed to decide under ₹2,000. Block 90 minutes a day, phone in a drawer, for the work that actually moves the business — menu engineering, P&L, the next outlet. One full day a week where you don't enter the kitchen and nothing burns down. *If the restaurant can't run a Sunday without you, you don't own a restaurant — you are the restaurant.*" },
  },

  retail_offline: {
    identity: { content: "Pick one buyer your store actually wins — the working mother stocking up before school reopens, the wedding-season gold buyer aged 45+, the cricket-mad dad buying his son's first bat. Name her on a card at the counter. Then fire the SKUs she ignores — the dead racks that sat through last EOSS, the brands your staff push only because the distributor pressured you. Track repeat % in a 60-day window and square-foot revenue by category. *A boutique trying to serve everyone is just a warehouse with a shutter.*" },
    x_factor: { content: "Walk ten regulars to the counter and ask why they didn't buy that same kurta on Myntra. Write their answer in their words — tailoring on the spot, exchange without arguing, the aunty who remembers their size. That sentence becomes your staff training, your signage, your WhatsApp Broadcast tagline. Build one barrier a copycat can't clone in 90 days: a stitching tie-up, an exclusive supplier SKU, a 7-day no-question exchange the mall chains won't match. Kill any one customer or corporate account above 25% of monthly billing." },
    marketing: { content: "Own one word in your 3km radius — \"the tailoring boutique,\" \"the wedding gold store,\" \"the kids store that fits.\" Refresh Google Maps photos monthly, add \"open now\" hours, chase reviews from every billed customer via WhatsApp. Run RWA society tie-ups in 5 nearby apartments — a stall at their festival, doorstep pamphlets with a QR to your catalogue. Segment your WhatsApp Broadcast by last-purchase month and send one offer they can repeat. Track cost-per-walk-in. *Stop boosting Instagram posts that bring likes from Lucknow when your shop is in Indiranagar.*" },
    sales: { content: "Retail sales is the counter staff converting walk-ins to bills — measure staff-wise conversion every week and fire the one who sits below 30%. Build a 5-question investigation script: occasion, budget range, who else they're shopping for, when they need it, what they bought last time. Train one disqualification line — \"this isn't for you, try the lighter range\" — it doubles trust and basket size. Bundle a tailoring credit or 6-month exchange into the price so the customer can't compare you with Amazon's cart on their phone." },
    financial: { content: "Calculate true gross margin per SKU category — not the distributor's MRP fantasy, the real number after EOSS markdowns, shrinkage and returns. Pay yourself a market salary first, then check what's left as owner profit. Hold 3 months of rent, salaries and GST in a separate account before any new range order. Identify the bottom 20% of SKUs by inventory turn — the stock sitting beyond 90 days — and clear them at cost this quarter. Rent above 12% of revenue is a slow bleed you'll feel only at season closing." },
    optimisation: { content: "Your chokepoint is usually the billing counter at 7pm or the back-store stockroom no one can find anything in. Map it for one week. Move trial rooms, add a second QR-based billing point, label every shelf by SKU code. Kill three tasks that shouldn't exist — the manual stock register your software already runs, the WhatsApp order forwarding through three staff, the daily cash tally done twice. Write one handover sheet so any staff can open the shop. Aim to remove 10–15 hours from your week." },
    scale: { content: "Before you sign the second store lease, name the one thing that breaks at 3× walk-ins. Usually it's you — the only person who knows supplier pricing, handles tailoring escalations and approves discounts above 10%. Or it's supply — your best-selling SKU goes out of stock every festival because the distributor prioritises larger MBOs. Map the constraint to time, team, system or supply. Hire and train a store manager who can run your existing shop without WhatsApp pings for 30 days before you even visit the new location." },
    owner_energy: { content: "Stop being the human price tag and discount approver. Write a one-page rule sheet: max discount per category, exchange window, return conditions, vendor payment days. Now your staff decides without calling you. Block one 90-minute deep-work slot every morning before the shutter opens — for buying decisions, margin review, supplier negotiation — phone on silent. Take one full Sunday off-shop each week with no WhatsApp checks. *If your store can't bill ₹1 lakh on a day you're sick, you don't own a business — you are the business.*" },
  },

  real_estate_broker: {
    identity: { content: "Pick one lane and one customer profile you actually win: NRI repeat-investors buying 2nd/3rd unit, IT couples upgrading from 2BHK to 3BHK in a 5km radius, or HNI plot-flippers in a named corridor. Not all three. Fire C-tier builders with 6-month commission delays, walkers who treat you as Google for floor plans, and society listings below your minimum ticket size. Your one-line answer names person, pincode, ticket size, and trigger. *If your WhatsApp has 40 builder groups and zero buyer segments, you're a lead-runner, not a broker.*" },
    x_factor: { content: "Why does the NRI close with you and not the cheaper portal-broker calling them at 11pm Dubai time? Write it in their words, recorded on a site visit. Build one named barrier: a builder relationship tier-map where 3 A-tier builders give you pre-launch access nobody on 99acres has. Cap any single builder or single client family below 25% of your annual GMV. *Builders selling direct post-RERA launch and Lodha/DLF channel teams cutting brokers after one site visit — that's the villain you're racing against.*" },
    marketing: { content: "Own one word in one pincode: \"Whitefield 3BHK resale\" or \"Lower Parel pre-launch.\" One offer the buyer repeats: \"Three shortlisted units in 48 hours, RERA-checked, no spam calls.\" One distribution channel with known cost per closure — not cost per lead. Track Magicbricks/99acres lead-cost per actual closure, not per call. Kill the portal where 7 other brokers are dialling the same number. Society RWA tie-ups and existing-client referrals beat paid leads at 1–3% closure. *Stop buying leads you can't out-call.*" },
    sales: { content: "Replace the property-list-PDF pitch with a 5-question investigation: budget band, decision timeline, who else decides, last property they rejected and why, what changes in their life in 12 months. Make the buyer state their own urgency. Offer a curated 3-unit shortlist with RERA and society-financials pre-checked — uncomparable to a portal dump. Disqualification line: \"If you're still 6 months from booking, I'll WhatsApp you monthly, not chase.\" Track days from first call to token, not leads in pipeline." },
    financial: { content: "True gross margin per deal after referral splits, channel-partner cuts, and the assistant who ran 14 site visits. Real owner-inclusive profit after your own salary at market rate, not after-the-fact. Hold 6 months of operating expenses in cash because builder commission cheques land 12–18 months post-booking. Track builder commission days outstanding per A/B/C builder — fire any C-tier builder above 270 days. *One March closure saving the year is not a business — it's a lottery ticket with a RERA number.*" },
    optimisation: { content: "Your chokepoint is almost always site visits — you personally driving every buyer to every project. Map it: how many site visits per closure, hours per visit, your hourly cost. Hand pre-qualified visits to a junior with a written shortlist-script and a WhatsApp-update template. Kill the 3 builder WhatsApp groups that produce zero closures, the portal you renewed out of habit, and the printed brochure run. Remove 10–15 hours/week. One written handover: how a new joiner runs a first site visit without you." },
    scale: { content: "At 3× lead volume, what breaks first — your phone, your site-visit calendar, or builder commission tracking? Map it. Most brokers break at the follow-up layer: 200 active prospects, no one chasing day-45 and day-90 buyers, pipeline rots. Constraint is usually team and CRM, not leads. Remove yourself from the first-site-visit seat and the commission-chase seat. Track pipeline-to-closed ratio per source — if society referrals close 8% and portals close 1.2%, scale the 8% channel and exit the 1.2% one." },
    owner_energy: { content: "Half your day is WhatsApp triage: which builder, which buyer, which RWA contact, which assistant question. Kill 50% with three rules — buyers below your ticket size go to junior, C-tier builders get a weekly digest not live replies, society chatter gets muted till evening. Block one 90-minute deep-work window daily for builder relationship building and NRI repeat-investor calls — the two activities that actually compound. One full day a month where junior runs all site visits and you don't pick up." },
  },

  healthcare_clinic: {
    identity: { content: "Pick one procedure-and-patient pair you actually win. \"Adult orthodontics for 28–45 IT professionals in Whitefield\" beats \"family dental clinic.\" Stop taking insurance TPAs that pay at 90 days and demand 30% discounts. Stop the loss-leader root canals you do to fill chairs. Fire the GP referrer who sends only low-ARPU consults that never convert to treatment plans. Your villain isn't Apollo — it's the founder who treats everyone who walks in. *The clinic that treats everyone gets remembered for nothing.*" },
    x_factor: { content: "What do patients tell their cousin about you that they don't say about Apollo? Capture it in their words from your last 20 Google reviews and WhatsApp follow-ups. One named barrier: a treatment protocol, a senior doctor's 15-year track record on one procedure, a follow-up system Apollo's volume can't match. Zero referring GPs above 25% of new patient flow, or the day they open their own clinic you lose a quarter of revenue. Audit which 3 GPs send what." },
    marketing: { content: "Own one word for one procedure in one pincode. \"Painless root canal in Koramangala\" is ownable. \"Best dental clinic\" is not. One distribution that works: society health camps with a tracked 30-60-90 day WhatsApp follow-up — measure camp-to-consult and consult-to-treatment-plan conversion, not footfall. Practo paid bumps without Google review velocity (4 new reviews per week minimum) is money lit on fire. Kill the Instagram Reels nobody saves. *Your villain is the patient who Googles symptoms at 11pm — get there first with one educational Reel per week on your one procedure.*" },
    sales: { content: "Your sales call is the first consult. Build a 5-question investigation the doctor or counsellor runs that makes the patient state their own urgency — \"how long has this stopped you sleeping, eating, working out?\" Package the treatment plan so it can't be compared rupee-for-rupee with the clinic down the road (include follow-ups, imaging, a named senior doctor). Disqualification line: \"if you're only here for a second opinion on price, we're not the right clinic.\" Track first-consult-to-treatment-plan conversion weekly. Below 40% means the consult is broken — not the price." },
    financial: { content: "Calculate true ARPU per procedure after consumables, lab outsourcing, doctor revenue-share, and TPA discount drag. Most clinics discover one \"flagship\" package loses money once you load doctor time honestly. Owner-inclusive margin — pay yourself a market salary first, then look at profit. Three months of operating expenses in cash before you buy the second chair or laser. Fire the TPA paying at 120 days and demanding 35% off. Fire the package priced for footfall, not margin. *Chair utilization without ARPU per chair-hour is vanity — a full chair losing ₹500/hour is worse than an empty one.*" },
    optimisation: { content: "The chokepoint is almost never the doctor — it's the front desk converting consult to treatment plan and chasing the no-show. Map one week: how many consults walked out without a treatment estimate? How many follow-up WhatsApps went unanswered past 48 hours? Kill the paper case sheets, kill the three WhatsApp numbers patients ping randomly, kill the manual appointment confirmations. One written handover for the receptionist on consult-to-plan conversion and no-show recovery. Target: 10–15 hours/week of doctor time freed from admin and chasing." },
    scale: { content: "At 3× patient flow, what breaks first — the senior doctor's calendar, the sterilisation cycle, the receptionist, or the cash flow because TPAs pay later than your salaries hit? Name it before you open chair two or branch two. The classic clinic break-point: the founder-doctor is the brand, and patients refuse the junior associate. Map your constraint to one of: doctor time, system (EMR/sterilisation), supply (implants/consumables), or cash (TPA receivables). Remove the founder from the chair on at least one procedure type before scaling location two." },
    owner_energy: { content: "Stop being the doctor and the manager and the marketing person in the same day. Cut 50% of daily decisions — pre-decide which cases you personally consult vs. which the associate handles, pre-decide the package pricing tiers so the receptionist quotes without asking. One 90-minute block, five days a week, blocked off the OPD calendar for clinical protocol review or one strategic call. One full day a week the clinic runs without you in the chair. *If the clinic can't run one Tuesday without you, you don't own a clinic — you are the clinic.*" },
  },

  education_school: {
    identity: { content: "Pick one student, one outcome, one parent. \"Class 8-10 CBSE students in [your area] whose parents already spend on tuition but want Maths-Science scores above 90.\" Not playschool kids, not JEE droppers, not adult English. Drop the subjects you teach badly. Kill the batch with 4 students dragging on. Fire the parent who haggles every term and pays late. Education founders dilute by adding subjects to fill seats — every subject you don't own makes BYJU's the easier choice. *Your batch list should make one type of parent feel this is built for their child only.*" },
    x_factor: { content: "One sentence a current parent says: \"Sir's teacher catches what my child doesn't understand before the test, not after.\" That is your refusal answer to \"free YouTube is enough.\" Name one barrier — a diagnostic test before enrolment, a parent-WhatsApp weekly progress note, a teacher who's been with you 5+ years. No single school tie-up or coaching chain partnership above 25% of fees. *BYJU's has crores in ads; you have the teacher who calls the parent at 9pm when the child failed a mock — they cannot copy that.*" },
    marketing: { content: "Own one word — \"weak-topic-fixer,\" \"board-toppers,\" \"slow-learner-friendly,\" \"NEET-repeater-specialist.\" One offer parents repeat in society WhatsApp groups: \"Free 3-day diagnostic, written report on what your child is missing.\" Pick ONE distribution channel and measure cost-per-enrolled-student: parent referral cash incentive, Google Maps reviews per branch, or society mom WhatsApp seeding. Stop boosting random Instagram reels. Track demo-to-enrolment % weekly. *If a mother in a society WhatsApp group cannot describe your centre in one line, you do not have marketing — you have flyers.*" },
    sales: { content: "The demo class is the sale. Stop \"selling\" — investigate. Five questions before quoting fees: What score is your child getting now? What score do you want by March? What have you already tried? What happens if nothing changes? Why now, not next term? Make the parent state their own urgency. Disqualify openly: \"If your child only needs YouTube, save the fee.\" Quote annual fee, not monthly — break comparison with the neighbour. *Parents don't buy tuition, they buy peace before the board exam — sell that, not your syllabus.*" },
    financial: { content: "Calculate true gross margin per student per year after teacher salary, rent, electricity, materials. Most centres think they make 40% — real number is 15–20%. Build a 12-month cashflow: April-June fee collection funds Dec-Feb lean months, not your next branch. Keep 4 months of fixed costs in cash before any expansion. Fire the batch with 60% utilization that you keep \"because we always had it.\" Stop annual discounts to parents who pay late anyway. *One fully-loaded batch beats three half-empty ones — empty seats are not free, they are paid for by your good teachers' unpaid overtime.*" },
    optimisation: { content: "The chokepoint is almost always you doing demo classes, parent calls, fee follow-ups, and teacher hiring yourself. Pick one — make a senior teacher run all demos with a written script and a 20% incentive on enrolment. Kill the WhatsApp group where 80 parents ask the same homework question — replace with one weekly recorded update. Stop hand-collecting fees; one payment link, one auto-reminder. Write one handover document for batch scheduling. *If you go on a 10-day holiday in May and enrolments stop, your centre is your job — not your business.*" },
    scale: { content: "What breaks at 3×? Not marketing — teachers. You cannot find 9 more teachers as good as your top 3, and the top 3 will leave to open their own centre in 2 years. Map the break: it's team and system, not demand. Build a teacher-training playbook so a B+ teacher delivers A-grade output. Lock your top teachers with revenue share, not just salary. Stop opening branch two until branch one runs at 85% batch utilization without you. *Education does not scale on students — it scales on teachers you can replace without parents noticing.*" },
    owner_energy: { content: "Stop taking every parent's call. Stop sitting in every demo. Stop approving every leave request. One 90-minute morning block, 5 days a week, for curriculum, teacher review, parent-NPS reading — phone off, no walk-ins. One full Sunday where the centre runs term-end parent meetings, demos, and fee collection without you on WhatsApp. Delegate the parent who calls 4 times a week to your centre head with a script. *The founder who personally counsels every parent at enrolment owns a coaching class — the one who doesn't owns a coaching business.*" },
  },

  events_weddings: {
    identity: { content: "Pick one bracket and one moment. Are you the ₹8L mid-budget Delhi sangeet decor specialist, or the ₹40L destination-Udaipur full-event planner? You can't be both. Fire the ₹2L \"family friend\" weddings that eat your November dates. Name the couple: \"We're for the bride whose mother already approved a ₹15L budget and who saw our work at her cousin's haldi.\" Track repeat-family rate — siblings and cousins should be 25%+ of bookings. *The vendor who serves every budget owns no calendar in season.*" },
    x_factor: { content: "Write the one sentence a past bride would WhatsApp her engaged friend: \"They didn't blink when MIL changed the mandap colour 4 days out.\" That's your refusal line against the 40%-cheaper local guy. Build one barrier a copycat can't clone fast — a signed network of 8 planners who refer only you, or a 200-wedding Instagram archive sorted by venue. No single planner should drive more than 25% of your bookings. *Pinterest brides don't pay for pretty — they pay for the vendor who survives the mother-in-law week.*" },
    marketing: { content: "Own one word in the planner network's head — \"reliable,\" \"calm,\" \"on-time,\" pick one. Your repeatable offer: \"Lock the date with 30% deposit, full vendor list confirmed in 14 days.\" One distribution channel done properly — vendor cross-referral cards traded with 12 planners and 8 photographers — beats four half-built channels. Measure Instagram-Reel-to-inquiry rate per post and cost per booked wedding from WedMeGood vs ShaadiSaga listings. *The planner network is your distribution — Instagram is just the proof they show the bride.*" },
    sales: { content: "Stop sending price lists. Build a packaged offer the bride can't line-item compare — \"Sangeet + Haldi décor, 3 venue visits, MIL-approval call included.\" Run a 5-question investigation on every inquiry: budget bracket, guest count, MIL involvement, date locked or flexible, who else they're talking to. Your disqualification line: \"If your budget is under ₹X and the date is in peak November, we're not your team.\" Demand 30% deposit at booking, 40% 30 days out, balance 7 days before. *Couples who can't commit a deposit can't commit to your calendar either.*" },
    financial: { content: "Calculate true margin per wedding after sub-vendor payouts, GST, and your time — most planners think they make 25% and actually clear 8%. Owner-inclusive profit means paying yourself a real salary before declaring profit. Hold 4 months of operating expenses in cash because May-August is dead. Fire the customer type that drags deposits past 30 days — they're financing themselves on your sub-vendors. Track season-month profitability separately from annual. *If November-February doesn't fund May-August, you don't have a business — you have a hobby with deposits.*" },
    optimisation: { content: "Your chokepoint is almost certainly you handling every vendor coordination call on event week. Map it: 10–15 hours/week of WhatsApp coordination, vendor confirmations, MIL hand-holding. Kill three tasks that shouldn't exist — manual vendor payment reminders, repeated venue-visit scheduling, custom quotes for inquiries below your bracket. Write one handover doc for your assistant covering vendor confirmation calls and deposit follow-ups. *Every hour you spend chasing the caterer's advance is an hour you're not closing next November's booking.*" },
    scale: { content: "Name what breaks at 3× bookings. For most wedding vendors it's not money — it's you. One photographer can't shoot three Saturdays in November. One planner can't be on three mandaps in one weekend. Map the constraint: team (need a second-shooter or junior planner), system (no CRM tracking deposits across 40 weddings), or supply (your 3 trusted decor sub-vendors are also overbooked). Remove yourself from one critical seat — vendor coordination or final venue walkthrough. *Season frenzy doesn't break the business — it breaks the founder who's still on every call.*" },
    owner_energy: { content: "In peak season you're making 200 micro-decisions a day — vendor confirmations, fabric colours, MIL escalations. Cut 50% by pre-deciding: standard vendor list per budget bracket, standard décor palette per theme, a written \"we don't change scope inside 7 days\" policy. Block one 90-min deep-work window 5 mornings a week before WhatsApp opens. Pick one day a month where your assistant runs all client calls and you don't touch the phone. *If the business can't survive you taking Sunday off in October, November will break you.*" },
  },

  construction_interior: {
    identity: { content: "Pick your one client: 3BHK ready-possession buyer in a named builder's tower, ₹15–25L turnkey, 90-day handover. Stop chasing sub-₹10L \"just-the-kitchen\" jobs, free 3D revisions, and contractor-led civil-only work where you carry warranty risk for someone else's masons. Fire the client who already \"has a contractor for civil, just need design.\" Your stop-doing list also kills: relatives' flats at cost, jobs without 30% advance, and any project where the husband says \"my wife will decide everything later.\" *The contractor-cousin will always be cheaper; your job is to make that comparison irrelevant before BOQ stage.*" },
    x_factor: { content: "Your refusal sentence comes from past clients in the same tower: \"they finished in 75 days, no snag list after Diwali.\" Name one barrier a copycat can't clone in 6 months — your in-house mason team on payroll (not daily-wage poachable), your tower-specific BOQ library, or your fixed-price-no-scope-creep contract. Map revenue: no single builder partnership or society should cross 25%. The villain is the mason poached mid-slab by the contractor next door. *On-time delivery is your moat — everyone else is selling renders.*" },
    marketing: { content: "Own one word: \"on-time\" or \"no-snag\" or \"tower-specialist.\" Your repeatable offer: \"3BHK turnkey, 90 days, fixed BOQ, no scope-creep surprises — ₹18L all-in.\" One distribution channel, measured: Instagram before/after Reels of the same room (not 15 different projects) with cost-per-qualified-site-visit tracked weekly. Kill the architect-cross-referral fantasy if it hasn't produced a paying lead in 6 months. Builder partnership tier map: which 3 builders refer monthly, which 10 you stop chasing. *Society WhatsApp beats Google Ads when your last client lives two floors above the next one.*" },
    sales: { content: "Stop sending BOQ on first meeting — that's how the cousin-contractor undercuts you line by line. Build a discovery: 5 questions forcing the client to state their own deadline (\"possession date?\"), their own pain (\"last flat that took 8 months — whose fault?\"), and their own budget ceiling. Offer a paid ₹15K design-lock deposit before any 3D. Disqualification line: \"if you're comparing us to your cousin's contractor, we're not the right fit.\" Enforce 30/40/30 milestone payments — advance, mid-execution, pre-handover. Final 10% is goodwill, not leverage." },
    financial: { content: "Calculate POST-execution margin per project, not as-quoted — scope creep and client negotiation eat 8–15% before you notice. Track working capital days: most interior firms run 90–120 days while vendors demand 30. Target 30%+ upfront collection on signing, 40% before site mobilisation. Kill the sub-₹10L project SKU — gross margin after mason overtime is negative. Owner-inclusive profit (after paying yourself a real salary) should be 12%+ on turnkey. Hold 3 months of fixed costs in cash before taking the next big project. *GST input mismatch on un-billed vendor cash is a silent 4–6% margin leak.*" },
    optimisation: { content: "Your chokepoint is almost always you on WhatsApp at 11pm approving tile samples and mason payments. Remove 10–15 hours/week by: killing client WhatsApp groups (one project manager per site, one weekly update video), a signed scope-creep change-order form before any \"can you also add\" gets quoted, and a vendor payment day (Tuesday only, not on-demand). Stop the daily site visit if your site supervisor is competent — go twice a week with a written checklist. Three tasks to kill: free revisions after design-lock, sample sourcing trips with clients, snag-list debates over WhatsApp voice notes." },
    scale: { content: "At 3× demand, what breaks first is not design capacity — it's your mason bench and your project manager. Map the constraint: can you run 8 simultaneous sites with current supervisors, or does quality collapse at 5? Remove yourself from final BOQ approval (set a margin floor instead) and from client handover meetings. Build a tower-specific BOQ library so estimation stops being bespoke. The named risk: one star site supervisor leaves and 4 projects stall. Pay him like a partner or build a second one before you sign the next contract." },
    owner_energy: { content: "Cut 50% of daily decisions: standing material specs per price tier (you don't re-pick tiles for every 3BHK), a vendor payment day, a fixed mason wage card. Block 9–10:30am for design-lock approvals and BOQ sign-offs — phone off, no site calls. One day a week (Wednesday), the business runs without you: site supervisor reports to PM, PM reports to a written tracker, you don't pick up. The decision you should never delegate: which client to fire mid-project. The decision you should never make: which colour grout. *If you're on site fixing snag lists at 8pm, you don't have a business — you have an expensive job.*" },
  },

  logistics_transport: {
    identity: { content: "Pick one lane and one customer profile you actually win on — say, Chennai-Hosur auto-component FTL for tier-2 OEM suppliers, or Mumbai-Pune cold-chain for pharma distributors. Fire the loss-making lanes where dead km crosses 35%, the aggregator loads where Rivigo or Delhivery is taking 25–30% off your freight rate, and the manufacturer paying past 90 days while your diesel bill is daily. One sentence: \"We run [lane] for [customer type] who needs [POD/temperature/timing promise].\" *If every lane on your board looks the same colour, you don't have a business — you have 40 trucks chasing whoever calls.*" },
    x_factor: { content: "Aggregators win on volume. You can't. Build one named barrier they can't copy in your chosen lane — a dedicated trailer pool parked at the customer's plant, a 4-hour POD upload rhythm, a return-load network with two broker partners that pushes your loaded-km past 85%. No single customer above 25% of revenue, because the day a ₹4Cr auto-component client switches to BlackBuck, you're done. Your customer should be able to say in one line why they refuse the 8% cheaper Delhivery quote." },
    marketing: { content: "Stop chasing IndiaMART leads. Own one word in one lane — \"the Hosur auto-parts guy,\" \"the Nashik pharma cold-chain guy.\" One distribution method that works: direct relationship sales to 30 named manufacturers and dealers in your lane, monthly plant visits, a WhatsApp broadcast to logistics heads with on-time % and POD turnaround numbers. Kill the broker network for new customer acquisition — it brings price-shoppers. Track cost-per-engaged-lead. *If your customer can't repeat your promise back to you in one sentence, your marketing is the aggregator's logo on their portal, not yours.*" },
    sales: { content: "Don't quote per-km until you've asked five questions: what's their current dead-km cost, what does a missed POD cost them per consignment, who at the plant gets the 2am call when a truck breaks down, what's their payment cycle reality, what would make them fire their current transporter tomorrow. Build an offer aggregators can't match — dedicated fleet, named driver pool, WhatsApp tracking group with the plant manager. Disqualify anyone demanding 90-day terms on day one. The price-shopper is the aggregator's problem now." },
    financial: { content: "Calculate true cost per km per lane — diesel, driver, tyre, maintenance, EMI, insurance, RTO — not the back-of-envelope ₹X figure your accountant gives you. Your real gross margin per loaded km is probably half what you think once dead km and 90-day payment financing cost are baked in. Fire the customer paying at 120 days, fire the lane where fuel-as-%-of-revenue crosses 45%. Hold three months of diesel and driver salary in cash. *The manufacturer paying you in 90 days is financing his working capital on your diesel pump.*" },
    optimisation: { content: "Name your chokepoint. For most fleet owners it's one of three — return-trip load matching (dead km bleeding 30%+), driver turnover (training a new driver costs ₹40K and a month of utilization), or POD-to-invoice cycle (POD sitting on someone's desk for 11 days before invoicing). Pick one. Kill three tasks — the daily diesel slip WhatsApp updates the owner reviews, the manual lane-pricing calls, the broker phone-trees. Build one written handover — the lane-utilization tracker — so your dispatch manager runs it without you." },
    scale: { content: "At 3× demand, what breaks first — trucks, drivers, working capital, or dispatch? For most ₹10Cr fleet owners it's working capital, because adding 20 trucks means ₹6Cr more locked in 90-day receivables before a single rupee comes back. Map the constraint. If it's drivers, build a retention bonus tied to loaded-km % and zero-accident months. If it's cash, fire the 90-day customers before you add capacity. Remove yourself from daily dispatch — that seat is the real ceiling, not the truck count." },
    owner_energy: { content: "Stop taking the 6am driver-no-show call. Stop approving every diesel slip. Stop quoting freight rates personally. Put a dispatch lead on the WhatsApp groups, give them a rate band they can quote inside, and a clear escalation line. One 90-minute block daily for the next lane, the next big customer, the next 10 trucks — not for putting out today's tyre-burst. One full day a week where the dispatch desk runs without your phone ringing. *If you're still the one calling the driver at 11pm, you don't own a fleet — the fleet owns you.*" },
  },

  professional_services: {
    identity: { content: "Pick the client you actually want to serve for the next five years and name them out loud: \"mid-size manufacturers in Peenya doing GST + ROC + transfer pricing\" or \"founder-led D2C brands raising Series A who need cap-table and ESOP work.\" Fire the ₹5,000 GST-return clients, the WhatsApp-query freeloaders, and the cousin's friend who pays in three months. Build one engagement letter per segment. *If your client list reads like a phonebook, your fee schedule reads like a discount coupon.*" },
    x_factor: { content: "Ask your top five retained clients: \"Why didn't you move to a bigger firm or a Vakilsearch?\" Their words become your refusal sentence — usually it's response time, partner-level access, or sector depth. Cap any single client at 25% of revenue or your practice IS that client. Build one named moat: a sector niche, a published view, a court/forum specialisation. Track owner-revenue share — if 80% of fees still need your signature, you don't have a firm, you have a job." },
    marketing: { content: "Own one word in your niche's head — \"the GST-notice CA,\" \"the MSME-arbitration lawyer,\" \"the IVF second-opinion doctor.\" Pick one channel and run it weekly for 12 months: LinkedIn niche updates (case-law digest, GST notification breakdowns, audit-calendar reminders) or peer-referral mapping inside your ICAI/BAR/IMA circle. Drop the \"we do everything\" website. Track lead-to-engagement conversion and cost per qualified enquiry. *A generalist brochure is a referral killer — your network can't refer what they can't describe in one line.*" },
    sales: { content: "Stop quoting hourly against ClearTax's ₹500. Build a fixed-scope engagement letter — \"Annual Compliance Package: ₹2.4L, these 14 deliverables, these exclusions\" — so the prospect can't price-compare on Google. Run a 5-question discovery: last notice received, last audit finding, board's biggest worry, what their current CA/lawyer missed, decision timeline. Add a disqualification line: \"We don't take clients under ₹2 Cr turnover.\" Kill the free WhatsApp consult — every query under scope gets a polite \"that's a separate engagement\" reply." },
    financial: { content: "Calculate fee realisation per billable hour by partner — most solo pros discover they're effectively earning ₹800/hour after write-offs and unbilled queries. Track days sales outstanding; in Indian professional services, 90+ days is the silent killer. Fire the bottom-quartile clients eating 40% of your time for 10% of revenue. Move top clients to annual retainers paid quarterly in advance. Owner-inclusive margin must hit 35%+ — if you're paying yourself last, the practice is subsidising the clients, not the other way round." },
    optimisation: { content: "Your bottleneck is you signing every opinion, every return, every discharge summary. Map one week — how many hours go to commodity work (GST filing, routine ROC, repeat OPD follow-ups) that an articled clerk, junior associate, or NP could do with a checklist? Kill three recurring tasks: the courtesy WhatsApp reply, the free \"quick review,\" the unbilled phone consult. Build one written SOP per service line so juniors can deliver without your signature on every page. Reclaim 10–15 hours weekly for advisory work that actually bills at premium rates." },
    scale: { content: "At 3× clients, what breaks first — your review capacity, your junior bench, your billing system, or your client-onboarding KYC? For most solo pros it's review: you become the human bottleneck for every deliverable. Name a second partner or senior associate empowered to sign on defined matters. Map which seat you must exit — usually \"first-draft author\" — and which one you must own — \"client-relationship and strategy.\" Without this split, your firm caps at whatever you personally can review in a 60-hour week." },
    owner_energy: { content: "You're answering client WhatsApps at 11pm and reviewing junior drafts at 6am — that's not dedication, that's a broken system. Block 9–10:30am daily for one deep-work matter — no calls, no queries, phone in drawer. Push all client WhatsApps to a shared inbox a junior triages. Pick one weekday where you take zero client calls — the practice runs on SOPs and your second-in-command. *If the practice can't survive your 24-hour silence, you don't have a practice — you have a permanent on-call shift.*" },
  },
}

// Helper: get the overlay for a {vertical, force} pair, or null if none exists.
export function getOverlay(
  vertical: VerticalValue | null | undefined,
  force: ForceKey,
): OverlaySnippet | null {
  if (!vertical) return null
  const v = PLAYBOOK_OVERLAYS[vertical]
  return v ? v[force] : null
}
